### Login
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email" : "tester@email.com",
    "password" : "welcome"
}

### LOGOUT 
DELETE http://localhost:5000/api/auth/logout HTTP/1.1
Content-Type: application/json

{
    "refresh_token":""
}

### Fetch new access token
POST http://localhost:5000/api/auth/refresh_token HTTP/1.1
Content-Type: application/json

{
    "refresh_token":""
}




### Create a Parking Lot
POST http://localhost:5000/api/parkinglots HTTP/1.1
Content-Type: application/json

{
    "lot_id": "MG01",
    "location": "M G Road",
    "small_spots_no": 8,
    "medium_spots_no": 5,
    "large_spots_no": 4,
    "small_spot_rate": 20.50,
    "medium_spot_rate": 30.81,
    "large_spot_rate": 40.00

}
### GET Booking by a user_id
GET http://localhost:5000/api/bookings?user_id=TESTER HTTP/1.1

### Create a Booking
POST http://localhost:5000/api/bookings HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGVzdGVyQGVtYWlsLmNvbSIsImlhdCI6MTY0MTk4ODE0OCwiZXhwIjoxNjQxOTg4NDQ4fQ.kMcwufxsQWjw9rRl5A8LjefeO9grvdxrSQ-3rIzC95E

{
    "date": "2021-12-28",
    "time_from": "11:30",
    "time_to": "12:00",
    "size": "small",
    "lot_id": "JY01"
}

### Create Parking Slots
POST http://localhost:5000/api/parkingslots/ HTTP/1.1
Content-Type: application/json

{
    "date" : "2021-12-28",
    "spotid" : "JY01-005"
}

### GET Parking Slots based on Query parameter
GET http://localhost:5000/api/parkingslots?date=2021-12-28&lot_id=JY01&size=small&time_from=11:30&time_to=12:00 HTTP/1.1
Authorization: Bearer <access token>

### Create a User
POST http://localhost:5000/api/register HTTP/1.1
Content-Type: application/json

{
    "email" : "tester@email.com",
    "password" : "welcome",
    "mobile": "9845123456"
}

